#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist, PoseStamped
from nav_msgs.msg import Odometry
from sensor_msgs.msg import LaserScan, Imu
import tf
import sys, select, os, signal, time, random
import numpy as np
if os.name == 'nt':
  import msvcrt
else:
  import tty, termios

BURGER_MAX_LIN_VEL = 0.22
BURGER_MAX_ANG_VEL = 2.84

WAFFLE_MAX_LIN_VEL = 0.26
WAFFLE_MAX_ANG_VEL = 1.82

LIN_VEL_STEP_SIZE = 0.01
ANG_VEL_STEP_SIZE = 0.1


e = """
Communications Failed
"""

c = 0

def signal_handler(signal, frame):
    twist = Twist()
    twist.linear.x = 0.0; twist.linear.y = 0.0; twist.linear.z = 0.0
    twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = 0.0
    pub.publish(twist)
    sys.exit(0)


def find_proper_direction(result, length, delta):
    beta = 1.316428268
    gamma = 0.2543680586
    tmp = np.array([],'float64')
    for i in range(length / 4):
        if i * delta + np.pi/4 < beta:
            tmp = np.append(tmp, .13/np.cos(i * delta + np.pi/4))
        elif i * delta + np.pi/4 < np.pi / 2:
            tmp = np.append(tmp, .5/np.cos(np.pi/4 - i * delta))
    tmp = tmp[:-1]

    compare = np.concatenate((tmp, tmp[::-1]))
 
    idx_1 = range(length / 8) + range(length * 7/8, length)
    idx_2 = range(length / 8, length / 4) + range(length * 3/4, length * 7/8)
    idx_3 = range(length / 4, length * 3/4)
    
    random.shuffle(idx_1)
    random.shuffle(idx_2)
    random.shuffle(idx_3)

    idx = idx_1 + idx_2 + idx_3
    
    for i in idx:
        flag = 1
        for j in range(length / 4):
            if result[(i + j - length / 8) % length] < compare[j] and result[(i + j - length / 8) % length] > 0:
                flag = 0
                break
        if flag:
            return i
    
    # terminates process when it cannot find proper direction
    pid = os.getpid()
    os.kill(pid, signal.SIGINT)

def process_laser(msg):
    global laser_flag, target
    if laser_flag: # parsing the LaserScan data collected from LiDAR 
        result = np.array(msg.ranges)
        target = find_proper_direction(result, len(result), msg.angle_increment) * msg.angle_increment
        laser_flag = 0

def process_odom(msg):
    global theta
    quaternion = (msg.pose.pose.orientation.x, msg.pose.pose.orientation.y, 
        msg.pose.pose.orientation.z, msg.pose.pose.orientation.w)
    theta = euler_from_quaternion(quaternion)



def euler_from_quaternion(quaternion):
    theta = tf.transformations.euler_from_quaternion(quaternion)[2]
    return theta

def process_imu(msg):
    global imu_flag
    twist = Twist()
    if imu_flag and abs(msg.linear_acceleration.x) + abs(msg.linear_acceleration.y) > 5:
        print "moving back"
        twist.linear.x  = -.1; twist.linear.y = 0; twist.linear.z = 0
        twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
        pub.publish(twist)
        time.sleep(1)

if __name__=="__main__":
    global laser_flag, target, theta, x, y, imu_flag
    if os.name != 'nt':
        settings = termios.tcgetattr(sys.stdin)

    imu_flag = 0
    rospy.init_node('turtlebot3_teleop')
    pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)
    sub_scan = rospy.Subscriber('scan', LaserScan, process_laser, queue_size=10)
    sub_odom = rospy.Subscriber('odom', Odometry, process_odom, queue_size=10)
    sub_imu = rospy.Subscriber('imu', Imu, process_imu, queue_size = 10)

    turtlebot3_model = rospy.get_param("model", "burger")
    signal.signal(signal.SIGINT, signal_handler)
    count = 0
    try:
        while(1):
            twist = Twist()
            if count % 2 == 0: # Finding the orientation to move ahead
                laser_flag = 1
                while laser_flag: # Waiting for laser scan
                    pass
                while target > np.pi:
                    target -= 2 * np.pi # making the range of target into between negative pi and positive pi
                twist.linear.x  = 0; twist.linear.y = 0; twist.linear.z = 0
                twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = target
                pub.publish(twist)
                time.sleep(1)

            elif count % 2 == 1: # Moving ahead for an half meter
                imu_flag = 1
                twist.linear.x  = 0.1; twist.linear.y = 0; twist.linear.z = 0
                twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
                pub.publish(twist)
                time.sleep(4)
                imu_flag = 0
                    
            count += 1
            
    except:
        print e

    finally:
        twist = Twist()
        twist.linear.x = 0.0; twist.linear.y = 0.0; twist.linear.z = 0.0
        twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = 0.0
        pub.publish(twist)

    if os.name != 'nt':
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)

