#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist, PoseStamped
from nav_msgs.msg import Odometry
from sensor_msgs.msg import LaserScan, Imu
import tf
import sys, select, os, signal, time, random
import numpy as np
if os.name == 'nt':
  import msvcrt
else:
  import tty, termios

BURGER_MAX_LIN_VEL = 0.22
BURGER_MAX_ANG_VEL = 2.84

WAFFLE_MAX_LIN_VEL = 0.26
WAFFLE_MAX_ANG_VEL = 1.82

LIN_VEL_STEP_SIZE = 0.01
ANG_VEL_STEP_SIZE = 0.1


e = """
Communications Failed
"""

c = 0

def signal_handler(signal, frame):
    twist = Twist()
    twist.linear.x = 0.0; twist.linear.y = 0.0; twist.linear.z = 0.0
    twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = 0.0
    pub.publish(twist)
    sys.exit(0)

def find_proper_direction(result, length, delta):
    global pid, obs_flag
    alpha = np.arctan(56.9/13.) 
    beta = np.arctan(13.8/17.8)
    tmp = np.array([],'float64')
    boundary = int(np.ceil(np.rad2deg(np.pi/2 - beta)))
    for i in range(boundary):
        if i * delta < np.pi / 2 - alpha:
            tmp = np.append(tmp, 0.569/np.cos(i * delta))
        else:
            tmp = np.append(tmp, 0.13/np.sin(i * delta))

    compare = np.concatenate((tmp[::-1][:-1], tmp))
 
    if obs_flag == 0:
        idx_1 = range(length / 8) + range(length * 7/8, length)
        idx_2 = range(length / 8, length / 4) + range(length * 3/4, length * 7/8)
        idx_3 = range(length / 4, length * 3/4)

    else:
        idx_1 = range(length / 8, length / 4) + range(length * 3/4, length * 7/8)
        idx_2 = range(length / 4, length * 3/4)
        idx_3 = range(length / 8) + range(length * 7/8, length)
        obs_flag = 0

    random.shuffle(idx_1)
    random.shuffle(idx_2)
    random.shuffle(idx_3)

    idx = idx_1 + idx_2 + idx_3
    
    for i in idx:
        flag = 1
        for j in range(1, boundary * 2):
            if result[(i + j - boundary) % length] < compare[j - 1] and result[(i + j - boundary) % length] > 0:
                flag = 0
                break
        if flag:
            return i
    
    # terminates process when it cannot find proper direction
    os.kill(pid, signal.SIGINT)

def process_laser(msg):
    global laser_flag, target
    if laser_flag: # parsing the LaserScan data collected from LiDAR 
        result = np.array(msg.ranges)
        target = find_proper_direction(result, len(result), msg.angle_increment) * msg.angle_increment
        laser_flag = 0

def process_odom(msg):
    global theta, odom_flag
    quaternion = (msg.pose.pose.orientation.x, msg.pose.pose.orientation.y, 
        msg.pose.pose.orientation.z, msg.pose.pose.orientation.w)
    theta = euler_from_quaternion(quaternion)
    odom_flag = 0

def euler_from_quaternion(quaternion):
    theta = tf.transformations.euler_from_quaternion(quaternion)[2]
    return theta

def process_imu(msg):
    global linear_flag, angular_flag, target, back_flag, obs_flag
    twist = Twist()
    if linear_flag and abs(msg.linear_acceleration.x) + abs(msg.linear_acceleration.y) > 8:
        print "Accelerometer Detected"
        obs_flag = 1
        linear_flag = 0
        twist.linear.x  = -.1; twist.linear.y = 0; twist.linear.z = 0
        twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
        pub.publish(twist)
        back_flag = 1
        time.sleep(1)
        back_flag = 0

    elif angular_flag and abs(msg.angular_velocity.z) > 0.3:
        print "Gyroscope Detected"
        obs_flag = 1
        angular_flag = 0
        twist.linear.x  = -.1; twist.linear.y = 0; twist.linear.z = 0
        twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
        pub.publish(twist)
        back_flag = 1
        time.sleep(1)
        back_flag = 0

if __name__=="__main__":
    global laser_flag, target, theta, x, y, linear_flag, angular_flag, pid, obs_flag
    if os.name != 'nt':
        settings = termios.tcgetattr(sys.stdin)
    pid = os.getpid()
    linear_flag = 0
    angular_flag = 0
    back_flag = 0
    obs_flag = 1
    rospy.init_node('turtlebot3_teleop')
    pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)
    sub_scan = rospy.Subscriber('scan', LaserScan, process_laser, queue_size=10)
    sub_odom = rospy.Subscriber('odom', Odometry, process_odom, queue_size=10)
    sub_imu = rospy.Subscriber('imu', Imu, process_imu, queue_size = 10)

    turtlebot3_model = rospy.get_param("model", "burger")
    signal.signal(signal.SIGINT, signal_handler)
    count = 0
    try:
        while(1):
            twist = Twist()
            while back_flag: # Guarantees robot to move back for a second when it requires
                pass
            if count % 2 == 0: # Finding the orientation to move ahead
                laser_flag = 1
                while laser_flag: # Waiting for laser scan
                    pass
                while target > np.pi:
                    target -= 2 * np.pi # making the range of target into between negative pi and positive pi

                twist.linear.x  = 0; twist.linear.y = 0; twist.linear.z = 0
                twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = target
                pub.publish(twist)
                time.sleep(1)

            elif count % 2 == 1: # Moving ahead for an half meter
                linear_flag = 1
                twist.linear.x  = 0.1; twist.linear.y = 0; twist.linear.z = 0
                twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
                pub.publish(twist)
                time.sleep(.5)
                angular_flag = 1
                time.sleep(3.5)
                angular_flag = 0
                    
            count += 1
            
    except:
        print e

    finally:
        twist = Twist()
        twist.linear.x = 0.0; twist.linear.y = 0.0; twist.linear.z = 0.0
        twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = 0.0
        pub.publish(twist)

    if os.name != 'nt':
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)

